name: farmer_welder
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python<=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - openpyxl
  - rpy2
  - pip
  - pip:
    - clarite
